name: minimum
description: "Android app launcher"
publish_to: 'none'

version: 2.2.6+155

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: 4.5.0
  slang_flutter: 4.5.0
  bloc: 9.0.0
  flutter_bloc: 9.1.0
  hydrated_bloc: 10.0.0
  equatable: 2.0.7
  get_it: 8.0.3
  path_provider: 2.1.5
  json_annotation: 4.9.0
  dynamic_color: 1.7.0
  collection: 1.19.1
  url_launcher: 6.3.1
  uuid: 4.5.1
  fast_immutable_collections: 11.0.3
  android_intent_plus: 5.3.0
  transparent_image: 2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: 2.4.15
  slang_build_runner: 4.5.0
  json_serializable: 6.9.4

flutter:
  uses-material-design: true