name: minimum
description: "Android app launcher"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  slang: 3.31.1
  slang_flutter: 3.31.0
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  hydrated_bloc: 9.1.5
  equatable: 2.0.5
  get_it: 7.7.0
  path_provider: 2.1.3
  json_annotation: 4.9.0
  dynamic_color: 1.7.0
  collection: 1.18.0
  url_launcher: 6.3.0
  uuid: 4.4.0
  fast_immutable_collections: 10.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: 2.4.11
  slang_build_runner: 3.31.0
  json_serializable: 6.8.0

flutter:
  uses-material-design: true